### ISSUE TITLE
TagsInput is not defined

### ISSUE THREAD

**Issue by DaleMckeown** [voerro/vue-tagsinput#11]
How can this component be used without NPM- for example via a CDN?

I've tried linking directly to the github dist files, and the NPM package files. But this throws a `TagsInput` is not defined error when registering the component with Vue:
![image](https://user-images.githubusercontent.com/1249673/38194904-7181544e-3672-11e8-8ba3-c82667a8c61f.png)

The build.js file is definitely being included:

![image](https://user-images.githubusercontent.com/1249673/38194968-d4db3fd2-3672-11e8-9026-b31350edb32f.png)

Despite this, there is no `TagsInput` in the window object:

![image](https://user-images.githubusercontent.com/1249673/38194884-4888c9c8-3672-11e8-8a64-70d418d59d12.png)

Here's a fiddle, replicating the issue with the example page for this repo: https://jsfiddle.net/eywraw8t/7148/.

**Comment by AlexMordred** [comment]
```
<div id="app">
    <tags-input element-id="tags"></tags-input>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.min.js"></script>
<script src="dist/build.js"></script>

<script>
    new Vue({
        el: '#app',
        components: { TagsInput },
    });
</script>
```

This is how I do it in the [live demo](https://voerro.github.io/vue-tagsinput/). You can see it for yourself [here](https://github.com/voerro/vue-tagsinput/blob/master/index.html).

**Comment by DaleMckeown** [comment]
Thanks for the quick reply.

This is exactly what I am doing, though. The jsfiddle above is literally a copy of the live demo.

**Comment by AlexMordred** [comment]
There are not script imports in your jsfiddle.

**Comment by DaleMckeown** [comment]
There are. In jsfiddle, you add  js/css as 'resources'. If you expand the tab on the left hand side, you'll see them:

![image](https://user-images.githubusercontent.com/1249673/38195745-1577181e-3677-11e8-9f8e-5f2a31f6ce28.png)

Like i said, the files are being included. Here's a screengrab of the jsfiddle iframe `<head>:`
![image](https://user-images.githubusercontent.com/1249673/38195787-525d4fd2-3677-11e8-8102-6592f37b1486.png)

**Comment by AlexMordred** [comment]
I have no idea what could that be. The jsfiddle doesn't work indeed, but it does work when I open the `index.html` file locally. Have you tried referencing the file locally?

Btw, I've just updated the package and renamed the js file to `voerro-vue-tagsinput.js`.

**Comment by DaleMckeown** [comment]
I don't understand it either - hence asking! It's as if the component isn't being attached to the global window object.

I'll give it a go locally and report back.

Yeah, renaming build.js isn't a bad shout. It may be worth renaming the component name in the global namespace as well - TagsInput could likely be used by other JS packages.

**Comment by AlexMordred** [comment]
Actually, I have this piece of code which conditionally attaches TagsInput to the global window object:

```
if (document.querySelector('#voerro-tags-input-demo-vqk6etkfjrcpsjg5')) {
    window.TagsInput = TagsInput;
}
```

I should probably rename the TagsInput to VoerroTagsInput to eliminate possible conflicts and remove the condition. Anyway this doesn't explain why your jsfiddle wouldn't work since you just copied the code from `index.html`.

**Comment by DaleMckeown** [comment]
Yeah, it's stange. I've tried it locally too, and it still gives the same error.

Forgive me, as I know little about ES6 modules (only just scratched the surface the last few weeks), but should the export be named?

```
 export default {
    name: 'tagsinput'
    ...
}
```

**Comment by AlexMordred** [comment]
I cloned the repository, opened `index.html` in the browser and everything works fine. Although, when I tried to reference the js file from GitHub directly it stopped working and I got this error `Loading failed for the <script> with source “https://raw.githubusercontent.com/voerro/vue-tagsinput/master/dist/voerro-vue-tagsinput.js”.`. I guess GitHub doesn't allow to use itself as a CDN. So you have to download the file and reference it locally to use it without npm. Can we close the issue?

Btw, I renamed it to VoerroVueTagsinput and removed the condition.

**Comment by DaleMckeown** [comment]
Thanks - I just saw the rename.

It's working now after the latest update:

![image](https://user-images.githubusercontent.com/1249673/38198005-de4a279e-3682-11e8-8329-c4585ce49c44.png)

Oddly, I can reference directly from Github just fine via `https://voerro.github.io/vue-tagsinput/dist/voerro-vue-tagsinput.js`!

It think it must have been either a conflict resolved by the rename, or the removal of the condition to attach to the window object.

Either way, thank you for looking into this so quick and getting it sorted.

**Comment by AlexMordred** [comment]
Oh, this is great! It's probably the condition. Thanks for reporting this :)

**Comment by DaleMckeown** [comment]
No worries.

I've put a request in with cdnjs to add the library - see if we can get it on a proper CDN :)

https://github.com/cdnjs/cdnjs/issues/12656

**Comment by AlexMordred** [comment]
Nice, thanks, I had no idea how it's done :D
