### ISSUE TITLE
Infinite Update Loop in watcher w/ expression existing-tags

### ISSUE THREAD

**Issue by Thaiten** [voerro/vue-tagsinput#115]
I have this error which causes the site to completely freeze in production
`[Vue warn]: You may have an infinite update loop in watcher with expression "existingTags"`

afair it worked in the past, but I am not sure when.

What puzzles me is that I don't use any watchers on the page, so I guess it's something in this package?

This is my input field
```
<tags-input element-id="tags"
		v-model="selectedTags"
		:existing-tags="existingTags"
		:typeahead="true"
		:autocomplete-always-open="true"
		:typeahead-hide-discard="true"></tags-input>
```

I specify the vars selectedTags and existingTags as empty arrays in the data property of the component.

In the mounted property, I perform an API call to fetch the existing tags. The returned data then gets handled in this method:

```
convertData(data){
			data.forEach(element => {
				this.existingTags.push({key: element.id, value: element.name})
			});
		}
```

Everything else in the file doesnt get executed or doesnt have any influence on the existingTags data.

I did add a before-adding-tag method, but I have it commented out and the erros still occurs.

Am I missing something here or is there really an error?

By the way, this happened in 2.4.1 and 2.4.2, im not quite sure if it did in prior versions.

**Comment by AlexMordred** [comment]
Thanks for a detailed report! Fixed in v2.4.3.
