### ISSUE TITLE
Configurable id for actual input field

### ISSUE THREAD

**Issue by pduersteler** [voerro/vue-tagsinput#118]
I could not find anything so I decided to open an issue for this.

The component renders the visible `<input type="text" placeholder="Add a tag">` that is being used to allow user input. It would be nice to be able to give this element an ID through configuration as well in order to be able to click a `<label for="id-of-visible-input-field">` to get the focus of the field. This would e.g. make selenium specs way easier because it is more simple to select the input field (either through the label or the id of the field directly).

**Comment by acirinelli** [comment]
Agree with @pduersteler and was going to open an issue as well. I'm trying to do something like this: ` @tag-added="focus('input_id')"` where `input_id` is the next seachable tag input. It make it easier for the user to hop from one to another without having to use the mouse.

**Comment by AlexMordred** [comment]
Added in the latest release. The new prop is called `input-id`.
