### ISSUE TITLE
Bug: Dropdown flickers when using typehead-url

### ISSUE THREAD

**Issue by acirinelli** [voerro/vue-tagsinput#125]
When using a `typehead-url` request, the search results flicker which is very dizzying for the user. Is there any way we can modify this so that the results are being updated, but not disappearing and reappearing with each query response?

![Flicker](https://user-images.githubusercontent.com/3673934/109862319-28775a00-7c15-11eb-8d24-7f14f916f8e4.gif)

**Comment by AlexMordred** [comment]
I saw your other PR, would you mind trying to solve this yourself?

**Comment by acirinelli** [comment]
https://github.com/voerro/vue-tagsinput/pull/131

**Comment by acirinelli** [comment]
Delete `this.searchResults = [];` in `searchTag()`
Add `this.searchResults = [];` in the first line of `doSearch()`

Since I already pushed my other displayField pull request into my fork master branch since I am using it, I cannot fork the repo again. So the code is propagating into my new branches to make this change.

**Comment by AlexMordred** [comment]
I checked the new commit, looks fine. I can merge everything as one piece as long as you fix the original PR.

**Comment by acirinelli** [comment]
ok I fixed the original pull request. Also set the default value of displayField to null as discussed since it is optional. Updated the readme file to incorporate this change.

**Comment by AlexMordred** [comment]
Thanks. Had to return `this.searchResults = [];` to `searchTag()` with an extra condition because the typeahead wasn't disappearing after you erase the last character in the input field in non-ajax mode. This shouldn't break your fix. WIll release everything soon.

**Comment by AlexMordred** [comment]
Released with `v2.6.0`
