### ISSUE TITLE
Remove selected tags from available tag list

### ISSUE THREAD

**Issue by matcartmill** [voerro/vue-tagsinput#13]
When selecting a tag it still shows as a selectable option in the tag list. Would love to see some functionality around not allowing a selected tag to display as an option when typing out a tag name.

Eg: I've got the following tags: `Web Development` and `JavaScript`. If I type `T` into the field, I get both tags. If I then select `Web Development` and press `T` again to start typing out a second tag, I still see `Web Development` as an option, and selecting it does not add it again.

Perhaps an attribute like `remove-selected-from-list` could be implemented?

Thanks.

**Comment by AlexMordred** [comment]
Thanks, that's a valid suggestion. I was thinking about it myself but I thought I wouldn't implement it until someone actually needs it haha. I'll work on it when I have some time.

**Comment by AlexMordred** [comment]
Just published a new version. Sorry it took me so long.

What I did was I hid the selected tags from typeahead by default since you couldn't add those tags twice anyway. Then I added an 'allow-duplicates' option in case you want to get the opposite behavior.
