### ISSUE TITLE
With a large number of tags, it stops working

### ISSUE THREAD

**Issue by fyapy** [voerro/vue-tagsinput#15]
`<tags-input element-id="tags" :existing-tags="{ 
	@foreach ($tagsList as $tag)
		 '{{$tag->id}}': '{{$tag->title}}',
	@endforeach
}"
:typeahead="true"></tags-input>`

At 70 it works, at 80 it does not work anymore
The browser displays `<!---->` in html
I am using laravel

**Comment by AlexMordred** [comment]
I just tried it with 100 tags and it works fine, didn't test it with Laravel & blade though.

I'm not familiar with the inline @foreach blade syntax you're using, but what you're doing doesn't seem exactly right to me. You should prepare/format your data in your backend, take a look at this https://laravel.com/docs/5.6/collections#method-mapwithkeys
