### ISSUE TITLE
No option to delete specific tag

### ISSUE THREAD

**Issue by simonjcarr** [voerro/vue-tagsinput#19]
If I have 5 existing tags and I want to delete the first tag. I have to delete all the tags and then re-enter the other 4 that I didn't want to delete.

Can you put a 'X' next to each existing tag to give the option to delete just that one tag.

Thank you

**Comment by simonjcarr** [comment]
Sorry,  just realised that I had not installed the CSS file.

**Comment by AnkurBegining** [comment]
@simonjcarr Have you tried to insert some other tag on the same place from where you have deleted. Is it possible to do this? I want to delete some specific tag and I would like to insert some other tag in the same place at the same place I have deleted. Is it possible to do that? Have you implemented using this library?
