### ISSUE TITLE
Capture v-model without pressing enter

### ISSUE THREAD

**Issue by otavio-paganotti** [voerro/vue-tagsinput#21]
Hello everyone,

I have a question about the component, but I'm not sure if it's here that will solve my problem.
I have a form where the user enters with an email address or more. But the tag is only created when the user presses the enter key on the keyboard.
I would like to know, if it is possible, if the user types only 1 email, without having to press enter, the component can capture the v-model of the component to send only this 1 typed email. And if he wants to send more than one email, the default behavior of pressing enter happens when he finishes typing the email.

**Comment by AlexMordred** [comment]
Hello.

This is not possible and I think this would be kind of an inappropriate behavior for an input of this type.
