### ISSUE TITLE
Show all existing tags

### ISSUE THREAD

**Issue by Meshz** [voerro/vue-tagsinput#22]
Hello, 

First of all, thank you for this component.

I was wondering if it's possible to show the complete list of existing tags when the input gets the focus and the "typeahead-activation-threshold" property is set to 0? This could be handy when the user as no idea of what to type in the input or to get an overview of existing tags.

Thank you for your feedback!

**Comment by AlexMordred** [comment]
Hi. Thanks for your suggestion, indeed this might be handy. I'll implement this later.

**Comment by AlexMordred** [comment]
I've just published a new version with the feature being implemented.
