### ISSUE TITLE
"Invalid regular expression" when entering new value with parentheses

### ISSUE THREAD

**Issue by Meshz** [voerro/vue-tagsinput#23]
Hello,

I found that when you enter a new value with parenthesis, you can see the following error in the console: `voerro-vue-tagsinput.js:295 Uncaught SyntaxError: Invalid regular expression: /Test (s`. On your demo page this is just printed in the console but in my app this makes the tab freeze.

I guess the problem is that you search the pattern on every character input. Maybe you should escape the parentheses to avoid considering it as a matched group. Any plan on resolving this?

Thank you for your help!

**Comment by AlexMordred** [comment]
Hi.

Thanks for reporting this! I'll take a look at it when I have time.

**Comment by AlexMordred** [comment]
Uploaded a fix with v1.9.1. Thanks again!
