### ISSUE TITLE
How can I make tag input required?

### ISSUE THREAD

**Issue by kilicbaran** [voerro/vue-tagsinput#30]
How can I achieve this: Tag input must be required. The user must submit at least one tag.

**Comment by AlexMordred** [comment]
Depends on how you submit your form. You should bind the taginput's value to a variable and check its length (it's an array) upon submission. Or did you mean like a standard browser "required"?

**Comment by kilicbaran** [comment]
Thanks. I will try the first option. At first, I thought about the standard browser required. However, I realized that it is not possible since it will only make the text input element (which is used to enter tags) required (not the tags) and that is not what I want.

**Comment by AlexMordred** [comment]
Alright. Please let me know how it goes and close the issues if you've solved your problem.
