### ISSUE TITLE
Option to cancel tags auto select

### ISSUE THREAD

**Issue by morangad** [voerro/vue-tagsinput#32]
Hi,
Tnx for this great gift.
Is it possible not to force selection of a auto complete tag? For example if I have a tag ABC and I'm typing A the ABC is automatically selected and unless I press ESC the ABC while be selected and pressing enter would select it when I actually want to a new tag (A). Maybe instead I can get all the auto complete option and only by actively selecting it it will replace my A with ABC and otherwise pressing enter would just add my A tag.

**Comment by AlexMordred** [comment]
Hi. I get what you mean, but I'm just not sure that's the kind of behavior most people would expect.

**Comment by morangad** [comment]
Hi Alexender,
After further thinking about it I think the best option is that with every
char entered by user the text will be added to tags list and deleted when
next char is entered and so on, this way what ever the user is typing is
the best match to auto complete.

**Comment by AlexMordred** [comment]
@morangad Sorry, I didn't get that.

**Comment by heroheman** [comment]
I kind of have the same problem.
If I have a tag called "WebDev" I can't add a tag called "Web"
Is there a way to add a "Add 'Web' as Tag" Button at the end or beginning of the dropdown?

**Comment by heroheman** [comment]
I just discovered this in your documentation:
>  Press Esc to discard the search results and then Enter to add a new tag the way you've typed it.
This is exactyl what I've been looking for. But it does not seem to work.
