### ISSUE TITLE
Option to add-tags-on-blur

### ISSUE THREAD

**Issue by libin-techversant** [voerro/vue-tagsinput#34]
Please add the option to add tags on blur just like `add-tags-on-comma`

**Comment by AlexMordred** [comment]
This might be tricky but I'll try. Just to clarify, typeahead/autocomplete won't work in this case and whatever is entered in the field at the moment of blur would be added, right?

**Comment by libin-techversant** [comment]
Its like I am entering something which is not in my existing tags and on blur it is added as a tag.

**Comment by AlexMordred** [comment]
Sorry for the very late reply. I implemented the feature and it will be present in the very next release. Thank you!
