### ISSUE TITLE
Remove selected tags with keyboard

### ISSUE THREAD

**Issue by nlhkabu** [voerro/vue-tagsinput#35]
It would be nice to be able to remove tags with the keyboard.

If we add `tabindex=0` [here](https://github.com/voerro/vue-tagsinput/blob/master/src/VoerroTagsInput.vue#L10), then we can add keyboard focus to the remove icons.

![screenshot from 2018-11-28 07-28-57](https://user-images.githubusercontent.com/3323703/49135720-74712100-f2df-11e8-813c-826beb3c6f6e.png)

*However* the workflow isn't ideal, because when using a keyboard the user must press tab to move through all the tags **before** being able to input a new tag.

It would be better if the focus started on the input, and then moved to the remove tag icons.

I'm happy to make a PR for this, if you can point me in the right direction :)

**Comment by AlexMordred** [comment]
You can delete the very last tag by pressing `backspace` when there's no text in the input. But I guess you meant navigating through the selected tags with the keyboard and to delete them?

**Comment by nlhkabu** [comment]
Yes, that's what I mean @AlexMordred.  To be able to use the keyboard to `tab` through the selected tags and delete whichever ones I want :)

**Comment by AlexMordred** [comment]
Closing for now as no one else seems to be in the need of this and I'm not too interested in implementing this either. But please feel free to make a PR.
