### ISSUE TITLE
Add 'focus' to wrapper

### ISSUE THREAD

**Issue by nlhkabu** [voerro/vue-tagsinput#36]
I am using this component with other standard form inputs.
On those form inputs I have a style for `:focus` where the border color changes.

It would be nice if I could style the wrapper class to have the same border color - e.g. it should have a dark border when I am interacting with the component.

I can't do this with CSS, because there is no way of selecting a parent.  It seems to me that the best way to do this is to add an additional class to the wrapper when the component is in active use.

Again, I am happy to make a PR for this, but would need to be pointed in the right direction (I am new to Vue.js)

Thanks

**Comment by AlexMordred** [comment]
There's a `wrapper-class` prop, and with this you can apply any custom class to the input. Let me know if that works for you.

**Comment by nlhkabu** [comment]
Hi @AlexMordred thanks for your answer.

I am already using the `wrapper-class` prop - but any class (and subsequent style) I apply is *always* there.  Is this correct?

What I want is for the wrapper class to be given an `active` class when (and only when) the user is using the component.  A bit like a native `:focus` state for an input.

Does this make sense?

Again, I'm happy to try to add this myself if pointed in the right direction. Thanks!

**Comment by AlexMordred** [comment]
Sorry, I know it's been over a year, but I've just implemented this feature (the wrapper element will get '.active' when the input field is focused. Will make a new release later today.

**Comment by nlhkabu** [comment]
Great, thank you!!!
