### ISSUE TITLE
change documentation to reflect last version

### ISSUE THREAD

**Issue by JoeZ99** [voerro/vue-tagsinput#37]
the doc states, when using cdn version of the library, that this line should be used

`https://cdn.jsdelivr.net/npm/@voerro/vue-tagsinput@1.8.0/dist/voerro-vue-tagsinput.js`

but `1.8.0` version doesn't have event firing.

the version which has events as described in the doc is `1.11.1`

that line needs to be updated

**Comment by AlexMordred** [comment]
It's a bit annoying changing the url with every release. That's why I have this line:

`IMPORTANT: Always grab the latest versions of the package from JSDELIVR, the ones provided in the examples above might be outdated. Same goes for Vue.js.`

**Comment by JoeZ99** [comment]
well, to my shame, I didn't go through the entire doc. Just copy/paste. :-(
