### ISSUE TITLE
Clear Search Results with ESC is not working

### ISSUE THREAD

**Issue by heroheman** [voerro/vue-tagsinput#39]
As I wrote in #32:
It seems that pressing esc is working, but it inmediatly triggers the `searchTag` function that is bind on `keyup`. If I change order it is working.
```
@keyup="searchTag"
@keyup.esc="ignoreSearchResults"
```

**Comment by AlexMordred** [comment]
Sorry for the very late reaction. Merged the PR. Thank you!
