### ISSUE TITLE
Issue with v-model data when selectedTags is empty

### ISSUE THREAD

**Issue by lainga9** [voerro/vue-tagsinput#43]
If the component is initialised with an empty array set for the v-model then when a tag is added and the tags-updated or tags-added is fired, the v-model array still remains empty.

I've tried cloning this repo and modifying your demo example and the problem still remains.

So if you were to update the selectedTags property to be an empty array and in your onTagAdded or onTagUpdated callbacks you console.log(this.selectedTags) you will see an empty array the first time you add a tag. If you delete the tag and then re-add the console will correctly show the array with one item in it.

Any thoughts?

**Comment by mitsuru793** [comment]
Me too. I see this problem when first adding a tag.

**Comment by AlexMordred** [comment]
Hey. Sorry for the late reply. I just released a new version and I was unable to reproduce the bug there. Please give a try again. Feel free to reopen this if the bug persists.

**Comment by marylein** [comment]
I have the same issue with the new version. The first tag is not showing up in the selectedTags, as soon as I add a second tag, the array will be shown correctly.

**Comment by shiwangebuzhidao** [comment]
I include this library into my page manually from a CDN, I already use the latest versio but the first time when I added a tag, the selectedTags is empty array and array is correct when I added a second tag.

**Comment by fguespe** [comment]
same here!

**Comment by AlexMordred** [comment]
Thanks guys! This has been fixed in v.2.0.2.
