### ISSUE TITLE
Tag Field Impacting Two Bindings

### ISSUE THREAD

**Issue by keithjkennedy** [voerro/vue-tagsinput#44]
I have created a component in my Laravel application and would like to use your Tags Input field. I have a Vue Class which, when called upon to create a form, it automatically generates an object titled "Reset" with the default field values. The idea being that the form can be reset at any point (e.g., the form is processed, form is cancelled half-way through completion). The issue I'm having is that this input assigns the "Tags" to both the bound field AND the reset field so when the reset truly needs to be applied, it's pushing the tags of the last form.

Here is the resulting object with reset:

`
class Form {
		constructor(data) {
			this.reset = data;

			for (let field in data) {
				this[field] = data[field];
			}

			this.errors = new Errors();
		}
		reset() {
			for (let field in this.reset) {
				this[field] = this.reset[field];
			}

			this.errors.clear();
		}
	}
`

Here is the original call:

` 
export default {
		data() {
			return {
				modal: {
					header: 'Add Organization',
					confirm: 'Create',
					cancel: 'Cancel'
				},
				organizations: {},
				form: new Form({
					id: '',
					name_long: '',
					name_short: {
						aliases: []
					},
				})
			}
		}
	}
`

And where your component is being used:

`
<tags-input v-model="form.name_short.aliases" placeholder="Add aliases here"></tags-input>
`

**Comment by AlexMordred** [comment]
Hey, sorry for the late reply. Sounds like this is not a problem with my component and you're dealing with 2 array objects pointing to the same data in memory. You need to deep clone your array instead simply re-assigning it.
