### ISSUE TITLE
Insert tag in between tags.

### ISSUE THREAD

**Issue by AnkurBegining** [voerro/vue-tagsinput#45]
@AlexMordred 
Is it possible to insert a tag in between other tags? Suppose I delete one specific tag and I want to insert some other tag at the same place of the deleted tag. Is it possible to do using vue-tagsinput? This feature would be great.

**Comment by AlexMordred** [comment]
Hey. Sorry for the late reply. Unfortunatelly, this is not possible and I'm not planning on implementing this at the moment.

**Comment by BananaAcid** [comment]
... or drag and drop support ;)
