### ISSUE TITLE
Can't create a new tag that that is similar to an existing tag when typeahead=true

### ISSUE THREAD

**Issue by SouthRibbleTech** [voerro/vue-tagsinput#49]
I pull my existing tags into my form so that users can choose from existing tags. However there is an issue when two tags are very similar. Take the example that a tag `v-bind-class` already exists, if I want to create a new tag `v-bind`, I am unable to, because when I click `enter` or `,` the `v-bind-class` tag is selected.

The only workaround is to add `v-bind-class`, then add `v-bind`, then delete `v-bind-class`

**Comment by mitsuru793** [comment]
I have the same problem.

**Comment by AlexMordred** [comment]
Hey. Sorry for the late reply. You should press `esc` to discard search suggestions and then if you press enter, `v-bind` will be inserted as a new tag.
