### ISSUE TITLE
Can one suggest tags based on synonyms?

### ISSUE THREAD

**Issue by rgranit** [voerro/vue-tagsinput#51]
Hi,

Looks like a great piece of software. Can one adapt the code to support synonyms for suggesting keywords?

Example:
`Tags: [ 'big', 'small' ] 
`

List of synonyms:
```
big = ['large', 'huge', 'enormous']
small = ['little', 'tiny', 'minute']
```

So when the user will search for 'large' the tag 'big' will be suggested.

Thanks!

**Comment by AlexMordred** [comment]
Hey. Sorry for the late reply. Could you provide some use cases for this? Can't think of any right off the top of my head.

**Comment by rgranit** [comment]
Hi @AlexMordred the usecase it a tagged search engine..

I was able to solve it editing the script so it will report what is the current input
```js

searchTag() {
            if (this.typeahead === true) {
                if (this.oldInput != this.input || (!this.searchResults.length && this.typeaheadActivationThreshold == 0)) {
                    this.searchResults = [];
                    this.searchSelection = 0;
                    let input = this.input.trim();
                    this.$emit('hidden-input', this.input);  // <- added this
                    ...

```
And after that using 'axios' call backend script that would find the synonym and return array of suggested tagwords

So I guess that I can close this issue :)
