### ISSUE TITLE
New tag is not added (or added existing tag), if existing tags have item with slug, equal to new tag text

### ISSUE THREAD

**Issue by maximkou** [voerro/vue-tagsinput#53]
**Options:**

typeahead = TRUE
existing-tags = [... see dataset below ...]

**Dataset:**

Existing tags: 
```javascript
{
    1: "first tag",
    2: "second tag"
}
```

**Workaround 1:**

1. Select existing tag 1, tag "first tag" is added. It's ok.
1. Input text "1", press enter. 

Result: Tag is not added, because slug of existing tag 1 is equal to new adding tag. It's not ok.

**Workaround 2:**
1. Input text "1", press enter. 

Result: added tag named "first tag", but expected "1".

[Related wrong code.](https://github.com/voerro/vue-tagsinput/blob/master/src/VoerroTagsInput.vue#L185)

**Comment by AlexMordred** [comment]
Hey. Sorry for the late reply. This is actually a pretty serious bug, thank you for reporting! A fix is done and will be present in the next release.
