### ISSUE TITLE
Enter or comma key not adding new tags on Chrome for Android

### ISSUE THREAD

**Issue by arcdelsol** [voerro/vue-tagsinput#61]
I understand this might be a Chrome Android keyboard issue. 
but no way to add a new tag when pressing enter/return (or comma key with the option enabled). 

Works on Firefox Android though

**Comment by BananaAcid** [comment]
"send" = enter, does only work if preceeded with a space.
Trick does not work with comma.

**Comment by AlexMordred** [comment]
Fixed the comma thing in version 2.0.1. Forgot to look into the Enter thing on Chrome, but I guess this is a Chrome issue indeed. Everything works fine for me in Firefox on Android. Closing this for now. Feel free to reopen if the comma issue persists or you have something else on your mind.

**Comment by BananaAcid** [comment]
the comma will use the letters as given to create the tag, the enter key will autocomplete .. on iOS ... on android chrome the enter does nothing still (except with a preceeded space but not autocomplete).

Are you going to look into it?
