### ISSUE TITLE
missing add-tags-on-space

### ISSUE THREAD

**Issue by BananaAcid** [voerro/vue-tagsinput#63]
It would be helpful, to enforce the user to only allow single tokens to be entered. At least to me it would be.

**Comment by ngmiduc** [comment]
yep, would be good !

**Comment by lindseydiloreto** [comment]
+100... I'd rather break tags between spaces rather than commas.

**Comment by AlexMordred** [comment]
This has been released under v.2.1.0.

**Comment by lindseydiloreto** [comment]
Excellent, thanks! 🍺
