### ISSUE TITLE
No autocomplete on Android

### ISSUE THREAD

**Issue by BananaAcid** [voerro/vue-tagsinput#65]
iPhone shows the pills and completes, Android does not.

**Comment by AlexMordred** [comment]
Fixed in version 2.0.1. Feel free to reopen if the issue persists.

**Comment by BananaAcid** [comment]
It changed to show the exact pill after the typed word matched the word from the autocomplete list. It wont show up while having only a few letters. And completing by pressing enter does not work.

**Comment by abhijeetrai5** [comment]
Using version `2.4.3` still facing the same problem
