### ISSUE TITLE
can we have support for array for existingTags ?

### ISSUE THREAD

**Issue by ctf0** [voerro/vue-tagsinput#7]

**Comment by AlexMordred** [comment]
Could you give me an example of a use case?

**Comment by ctf0** [comment]
atm the lib use object of `key : value` where in laravel u would mostly use `->pluck('something')` and you would get a `index : value`

**Comment by AlexMordred** [comment]
I made it this way thinking the `key` would be a slug or an id of a tag and the `value` would be a visual representation (text).

You can do this instead of pluck to achieve what you want:

```
->mapWithKeys(function ($item) {
return [$item['value] => $item['value']];
});
```

**Comment by ctf0** [comment]
awesome, many thanx
