### ISSUE TITLE
Change 'Discard Search Results' option to 'Add New Tag' event

### ISSUE THREAD

**Issue by arcdelsol** [voerro/vue-tagsinput#71]
'Discard Search Results' doesn't seem very intuitive.
Seems to be better to change this option to 'Add a new tag' when selected/highlighted with the keyboard. 
eg.
When I want to add a tag called 'Shape' but a tag called 'Shape of Despair' already exists then I can't do so when I press enter key because it defaults to the already existing tag. If there is a 'Add new tag' selection then this fixes the problem.

**Comment by ranaclyde** [comment]
+1

**Comment by AlexMordred** [comment]
The translation thing has been released under v.2.1.0. As for the the other thing, you can press ESC to discard search results, so I'm not sure this would be such a useful change.

**Comment by AlexMordred** [comment]
Closed due to no further answers/requests.
