### ISSUE TITLE
input on change

### ISSUE THREAD

**Issue by vahidhedayati** [voerro/vue-tagsinput#73]
Please can you add the following to your VoerroTagsInput.vue
```
      <input type="text"
             ref="taginput"
             :placeholder="placeholder"
             v-model="input"
             @input="onChange"
```

then the following:

```
  methods: {
            onChange() {
                this.$emit('key-press', this.input);
            },

```

This allows the end call to watch what user is putting in as part of input and finely render list as per input

**Comment by AlexMordred** [comment]
This has been released under v.2.1.0.
