### ISSUE TITLE
make the key value mapping dynamic:

### ISSUE THREAD

**Issue by vahidhedayati** [voerro/vue-tagsinput#74]
```   let newTag = {
                            key: '',
                            value: text,
                        };

                        const searchQuery = this.escapeRegExp(
                            this.caseSensitiveTags
                                ? newTag.value
                                : newTag.value.toLowerCase()
                        );
```

Change to something like this:
```
  export default {
        props: {
           keyField: {
                default: 'key'
            },
            valueField: {
                default: 'value'
            },
            remoteKey: {
                default: ''
            },
            remoteValue: {
                default: ''
            },
     },
,
        computed: {
            currentValue() {
              return (this.remoteValue ? this.remoteValue : this.valueField)
            },
            currentKey() {
                return (this.remoteKey ? this.remoteKey : this.keyField)
            }
        },

```
Then:

```
let newTag = {
                            this.keyField: '',
                            this.valueField: text,
                        };

                        const searchQuery = this.escapeRegExp(
                            this.caseSensitiveTags
                                ? newTag[this.valueField]
                                : newTag[this.valueField].toLowerCase()
                        );
```

and
```
  if (selectedTag.key === tag.key && compareable.search(searchQuery) > -1) {
                        return true;
                    }
```

to
```
  if (selectedTag[currentKey] === tag[keyField] && compareable.search(searchQuery) > -1) {
                        return true;
                    }
```

It still all works and allows end user to define what their actual data types are for both storing and capturing when doing auto complete part.

The `remoteKey` `remoteValue` can be defined by user differently to `keyField` and `valueField`  

Computed value decides if it is blank to use keyField instead of remoteKey - but in the end the auto complete list can match these keys values and the stored newTags can have relevant key value pairing.
Anywhere you have `.key ` `.value` needs updating when it deals with selected or auto complete data or existingData should I say that should use `object[currentValue]` and  `object[currentKey]`  instead. Where it is related to output i.e. newTag or tag then that should be `object[keyField]` and `object[valueField]`. 

Working on a auto complete locally and had to go through all this pain - data differences in what is sent modelled etc

**Comment by AlexMordred** [comment]
Sorry, I don't quite get what you're talking about. Also, maybe consider making a PR for this?

**Comment by vahidhedayati** [comment]
Sure thing I have done some additional work on this, during this cold week I will get some time to put something together ;)

**Comment by vahidhedayati** [comment]
a PR has been sent - sorry it happened twice I did fork earlier but wasn't paying attention had an older copy of project in repo - redone it all - and new PR has only new additional changes to latest - [this gist page outlines changes introduced](https://gist.github.com/vahidhedayati/3f27db7fb8a12f24a8a5102bae69bc06)

I think currently the keyField and valueField if not defined default to id/name ? I think that is what you had previosusly or expected - the remoteKey / remoteValue do not have to be defined - if defined it will look for those key values from the remote search screen which could be any key
so `remoteKey='remoteCityId'`  and we want to store in our tagsInput array as keyField='myCityId'  - 

The` key/value` fields are what to store it on array of tagsInput the `remote key/value` is  what is coming as part of search and the changes massage from remote to what user expects to save object as and `remoteCityId` appears as `myCityId` in the json array of selected tags input

The disabled is to stop users adding new if form is in display mode.
