### ISSUE TITLE
make the value easy to explode in php backend

### ISSUE THREAD

**Issue by Tukizz** [voerro/vue-tagsinput#84]
this tags input data output like  
```json
[  
  {"key" : "", "value" : "car1"},  
  {"key" : "", "value" : "car2"},  
  {"key" : "", "value" : "car3"}  
]
```

how to make this data converted like this 
```
[car1, car2, car3]
```
i want to convert like that because for easy to explode in PHP function

if you have a suggest let me know thanks

**Comment by AjithLalps** [comment]
Same question

**Comment by AjithLalps** [comment]
I got the same by little extra effort. I just iterated through the array of objects and save them to the field again like below.

```vue
let list = [];
$.each(this.form.meta_keywords, function(key, value) {
	list.push(value.value);
});
this.form.meta_keywords = list;
```

**Comment by AlexMordred** [comment]
@Tukizz unfortunately, you'll have to do the extra bit of work like @AjithLalps has suggested. The current logic allows you not only to add existing tags, but also to create new tags. If the `key` is empty, that's a sign for your backend that that tag does not exist yet and should be created.

**Comment by benedict-w** [comment]
@AlexMordred Is there anyway to bind the v-model differently in Vue so that the component submits these values, rather than having to do it on the backend?

**Comment by AlexMordred** [comment]
@benedict-w I'm not sure I understand you right, could you elaborate?

**Comment by benedict-w** [comment]
Sorry - I'm just trying to find out if there is anyway to submit these as an array of keys rather than an array of objects. i.e. So that the HTML input would behave as if it were a standard multi-select (or other array input), and so that I do not have to refactor the backend.

**Comment by AlexMordred** [comment]
@benedict-w unfortunately this is not possible. You can format the data on the frontend side before sending it to the backend. What you're saying implies having multiple `<input type="hidden" name="tags[]" value="tag-id">` inputs, one input per a selected tag, right? (this way you would get an array on the backend).

**Comment by benedict-w** [comment]
@AlexMordred Ah yes - of course you are correct. Thanks!
