### ISSUE TITLE
Key issure and update suggest

### ISSUE THREAD

**Issue by ALXLight** [voerro/vue-tagsinput#9]
Hello. 
oldTags is not handy and can be used only once, at component creation.
I reworked it to catch changes of tags from outside of component. I can send this changes to you if you're interested in it

**Comment by AlexMordred** [comment]
Hello.

There is `v-model` support already, so I'm not quite sure what you mean. Could you make a pull request so I could see the changes you made?

**Comment by ALXLight** [comment]
A i understood, any changes of bound variable from outside does not affect tags in component. Correct me if it is not true.
Send pull request

**Comment by AlexMordred** [comment]
Alright, I understand what you mean now. Thanks for pointing it out. I'll implement the functionality when I have time, can't accept your pull request the way it is though, but I'll keep it for reference for now.

**Comment by AlexMordred** [comment]
Implemented the functionality & updated the package. Thanks again.
