### ISSUE TITLE
typeahead-show-on-focus seems not to work.

### ISSUE THREAD

**Issue by Jihun0109** [voerro/vue-tagsinput#91]
New version v.2.2.0 introduced typeahead-show-on-focus option and it is enabled by default.
I am using "@voerro/vue-tagsinput": "^2.2.0" and typeahead-show-on-focus option is not working for me. I also tried to set the props to true but no luck. What action I expected is it will show dropbox if I click inputbox without typing any search suggestion. How can I do it?

**Comment by AlexMordred** [comment]
@Jihun0109 it will only show if you have something typed into the input and there are matches. I guess it would be better to show all the available options in case nothing is typed in?

**Comment by Jihun0109** [comment]
Yes, I need it displaying options when it gets focus without typing because we might don't know what the suggestion words are.

**Comment by AlexMordred** [comment]
Ok, I think the way it works now can be considered a bug. I'll take a look at it.

**Comment by Jihun0109** [comment]
To make it working we should use typeahead-always-show props and adjust the value whenever input gets and lost focus.

<tags-input
                  element-id="tags"
                  v-model="selectedTags"
                  :existing-tags="existingTags"
                  :typeahead="true"                  
                  :only-existing-tags="true"
                  :typeahead-hide-discard="true"
                  :typeahead-show-on-focus="true"
                  :typeahead-always-show="typeaheadAlwaysShow"
                  :typeahead-style="'dropdown'"
                  @tags-updated="updateTags"
                  @focus="tagboxFocused"
                  @blur="tagboxBlured"                  
                ></tags-input>`
....
tagboxFocused() {
           this.typeaheadAlwaysShow = true;
    },
    tagboxBlured() {
           this.typeaheadAlwaysShow = false;
    },

**Comment by AlexMordred** [comment]
Actually, I've just realized something. You just need to set the `typeahead-activation-threshold` to `0` and it'll work the way you need it with the focus (the default value is `1`). Please close the issue if this solves your problem.

**Comment by Jihun0109** [comment]
Cool, it works
