### ISSUE TITLE
Vue Warn: direct mutation of `existingTags`

### ISSUE THREAD

**Issue by homersimpsons** [voerro/vue-tagsinput#94]
Hello, thank you for your awesome component.

I'm using it on a project and came across an issue (that do not break anything).

When using `typeahead-url` Vue shows a warning:

```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "existingTags"
```

I guess this is because of the assignation here at least https://github.com/voerro/vue-tagsinput/blob/e4ef0fb1d0de6041c7ba0ae43b87cc3ad48f97bd/src/VoerroTagsInput.vue#L504

**Comment by AlexMordred** [comment]
Oh, yeah, you're right Thanks, I'll take a look when I have time.

**Comment by AlexMordred** [comment]
Will be fixed in the next release.
